import fs from "node:fs";
import path from "node:path";

// --- URL parity: 301 every legacy permalink to its new route -------------------------
// redirects/url-map.json is generated by scripts/migrate.py. These run on the standard
// Next.js Node server (localhost, Vercel, or a self-hosted container — identical behaviour).
const mapPath = path.join(process.cwd(), "redirects", "url-map.json");
const parity = fs.existsSync(mapPath) ? JSON.parse(fs.readFileSync(mapPath, "utf8")) : [];

// --- Environment isolation -----------------------------------------------------------
// Every host-dependent value is read from process.env so the same build runs unchanged
// on localhost today and in a Docker container later — just swap the env vars.
const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://thebusinesstrades.com";
const siteHost = (() => {
  try { return new URL(SITE_URL).hostname; } catch { return "thebusinesstrades.com"; }
})();

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  trailingSlash: false,

  // Cloud-agnostic build. `standalone` emits a self-contained server bundle in
  // .next/standalone (server.js + traced node_modules) for an easy future Docker image.
  output: "standalone",

  images: {
    // Migrated media is copied into /public/uploads and served as static files.
    unoptimized: true, // serve images as-is (no optimizer); works on any static host
    remotePatterns: [
      { protocol: "https", hostname: siteHost },
      // Brand logos served by Clearbit's logo CDN, keyed to each tool's official domain.
      { protocol: "https", hostname: "logo.clearbit.com" },
      // YouTube video thumbnails (videos_section.videos_image).
      { protocol: "https", hostname: "img.youtube.com" },
      { protocol: "https", hostname: "i.ytimg.com" },
    ],
  },

  async redirects() {
    return parity.map((r) => ({
      source: r.source,
      destination: r.destination,
      permanent: r.permanent ?? true,
    }));
  },
};

export default nextConfig;
