/**
 * content.ts — build-time MDX reader (Server Components / generateStaticParams only).
 * Reads the .mdx generated by scripts/migrate.py out of /content, parses frontmatter with
 * gray-matter. No client bundle, no database — fully static.
 */
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import type {
  BaseFrontmatter, MdxDoc, HomeAcf, BusinessToolAcf, CategoryAcf,
  ToolCategory, ToolCardRef, RedirectRule,
} from "./types/interfaces";

const CONTENT = path.join(process.cwd(), "content");

function listMdx(subdir: string): string[] {
  const dir = path.join(CONTENT, subdir);
  return fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith(".mdx")) : [];
}

export function loadDoc<T = Record<string, unknown>>(subdir: string, file: string): MdxDoc<T> {
  let raw = fs.readFileSync(path.join(CONTENT, subdir, file), "utf8");
  if (raw.charCodeAt(0) === 0xfeff) raw = raw.slice(1); // strip BOM so gray-matter sees the --- fence
  const { data, content } = matter(raw);
  const fm = (data ?? {}) as BaseFrontmatter<T>;
  return { slug: fm.slug ?? file.replace(/\.mdx$/, ""), frontmatter: fm, body: content };
}

export function loadAll<T = Record<string, unknown>>(subdir: string): MdxDoc<T>[] {
  const docs: MdxDoc<T>[] = [];
  for (const f of listMdx(subdir)) {
    try {
      docs.push(loadDoc<T>(subdir, f));
    } catch (err) {
      // A single malformed file must not 500 an index/listing page.
      console.error(`[content] skipped ${subdir}/${f}: ${(err as Error).message}`);
    }
  }
  return docs.sort((a, b) => (b.frontmatter.date ?? "").localeCompare(a.frontmatter.date ?? ""));
}

/* ---- business tools (CPT) ---- */
export const toolSlugs = (): string[] => listMdx("tools").map((f) => f.replace(/\.mdx$/, ""));
export const getAllTools = (): MdxDoc<BusinessToolAcf>[] => loadAll<BusinessToolAcf>("tools");
export const getTool = (slug: string): MdxDoc<BusinessToolAcf> =>
  loadDoc<BusinessToolAcf>("tools", `${slug}.mdx`);

/* ---- homepage ---- */
export const getHome = (): MdxDoc<HomeAcf> => loadDoc<HomeAcf>("home", "home.mdx");

/* ---- static pages ---- */
export const pageSlugs = (): string[] => listMdx("pages").map((f) => f.replace(/\.mdx$/, ""));
export const getPage = (slug: string): MdxDoc => loadDoc("pages", `${slug}.mdx`);

/* ---- blog ---- */
export const postSlugs = (): string[] => listMdx("blog").map((f) => f.replace(/\.mdx$/, ""));
export const getAllPosts = (): MdxDoc[] => loadAll("blog");
export const getPost = (slug: string): MdxDoc => loadDoc("blog", `${slug}.mdx`);

/* ---- tool -> lightweight card ---- */
export function toolCard(t: MdxDoc<BusinessToolAcf>): ToolCardRef {
  const acf = (t.frontmatter.acf ?? {}) as Record<string, unknown>;
  return {
    title: t.frontmatter.title,
    slug: t.slug,
    route: t.frontmatter.route || `/tools/${t.slug}`,
    logo: (acf.logo as string) || t.frontmatter.featured_image,
    rating: (acf.review_ster as string | number) ?? (acf.rating as string | number),
    excerpt: t.frontmatter.seo?.description,
    affiliate_url: t.frontmatter.affiliate_url,
  };
}

/* ---- categories: derived from each tool's frontmatter.categories ---- */
export function getToolCategories(): { name: string; slug: string; count: number }[] {
  const map = new Map<string, { name: string; slug: string; count: number }>();
  for (const t of getAllTools()) {
    for (const c of t.frontmatter.categories ?? []) {
      if (!c?.slug) continue;
      const e = map.get(c.slug) ?? { name: c.name || c.slug, slug: c.slug, count: 0 };
      e.count += 1;
      map.set(c.slug, e);
    }
  }
  return [...map.values()].sort((a, b) => b.count - a.count || a.name.localeCompare(b.name));
}

export const categorySlugs = (): string[] => {
  const fromTools = getToolCategories().map((c) => c.slug);
  const fromFiles = listMdx("categories").map((f) => f.replace(/\.mdx$/, ""));
  return [...new Set([...fromTools, ...fromFiles])];
};

export function getCategory(slug: string): ToolCategory {
  let intro: MdxDoc<CategoryAcf> | null = null;
  try {
    intro = loadDoc<CategoryAcf>("categories", `${slug}.mdx`);
  } catch {
    /* derived-only category (no dedicated .mdx) */
  }
  let name = intro?.frontmatter.title || "";
  const tools: ToolCardRef[] = [];
  for (const t of getAllTools()) {
    const match = (t.frontmatter.categories ?? []).find((c) => c.slug === slug);
    if (match) {
      if (!name) name = match.name || slug;
      tools.push(toolCard(t));
    }
  }
  return {
    name: name || slug,
    slug,
    route: `/category/${slug}`,
    description: intro?.frontmatter.seo?.description,
    acf: intro?.frontmatter.acf,
    tools,
  };
}

/* ---- related tools (same category -> top-rated fallback), current excluded ---- */
export function getRelatedTools(currentSlug: string, limit = 3): ToolCardRef[] {
  const all = getAllTools();
  const current = all.find((t) => t.slug === currentSlug);
  const currentCats = new Set(
    (current?.frontmatter.categories ?? []).map((c) => c?.slug).filter(Boolean) as string[]
  );
  const ratingOf = (t: MdxDoc<BusinessToolAcf>): number => {
    const acf = (t.frontmatter.acf ?? {}) as Record<string, unknown>;
    return Number(String(acf.review_ster ?? acf.rating ?? "").replace(/[^\d.]/g, "")) || 0;
  };
  const pool = all.filter((t) => t.slug !== currentSlug);
  const sameCat = pool.filter((t) =>
    (t.frontmatter.categories ?? []).some((c) => c?.slug && currentCats.has(c.slug))
  );
  const picked = [...sameCat].sort((a, b) => ratingOf(b) - ratingOf(a)).slice(0, limit);
  if (picked.length < limit) {
    const have = new Set(picked.map((t) => t.slug));
    const rest = pool.filter((t) => !have.has(t.slug)).sort((a, b) => ratingOf(b) - ratingOf(a));
    for (const t of rest) {
      if (picked.length >= limit) break;
      picked.push(t);
    }
  }
  return picked.slice(0, limit).map(toolCard);
}

/* ---- URL parity (consumed by next.config.mjs redirects()) ---- */
export function getRedirects(): RedirectRule[] {
  const p = path.join(process.cwd(), "redirects", "url-map.json");
  return fs.existsSync(p) ? (JSON.parse(fs.readFileSync(p, "utf8")) as RedirectRule[]) : [];
}
