/**
 * interfaces.ts — content models for the MDX generated by scripts/migrate.py.
 *
 * The Python transformer writes YAML frontmatter whose top-level shape is `BaseFrontmatter`
 * and whose `acf` payload is one of the per-template shapes below. Keep these in sync with
 * config.POST_TYPE_ROUTES and the ACF field names recovered from the legacy DB.
 *
 * NOTE: a few legacy ACF keys carry original typos (e.g. `review_titie`, `sectoin_6_button`).
 * They are preserved verbatim so the migration is lossless; normalise in a mapper if desired.
 */

export type ISODate = string;
export type PostType = "businesstool" | "page" | "post";

export interface SeoMeta {
  title: string;
  description?: string;
  canonical?: string;
  ogImage?: string;
}

export interface AffiliateLink {
  label: string;
  url: string;            // preserved byte-for-byte from source; never rebranded
  target?: "_blank" | "_self" | string;
  rel?: string;           // components inject "sponsored nofollow noopener"
}

export interface TermRef {
  name: string;
  slug: string;
}

export interface CtaButton {
  label: string;
  url: string;
}

/** Common frontmatter on EVERY generated .mdx, generic over its ACF payload. */
export interface BaseFrontmatter<TAcf = Record<string, unknown>> {
  title: string;
  slug: string;
  type: PostType;
  template?: string;            // legacy _wp_page_template, if any
  route: string;                // new Next.js path, e.g. "/tools/deel"
  original_url: string;         // legacy permalink (for the parity map / audit)
  date?: ISODate;
  modified?: ISODate;
  seo?: SeoMeta;
  featured_image?: string;      // "/uploads/..."
  youtube_url?: string;         // first embedded video, if any
  affiliate_url?: string;       // primary outbound offer (guardrailed)
  affiliate_links?: AffiliateLink[];
  categories?: TermRef[];
  acf?: TAcf;
}

/** A loaded MDX file: parsed frontmatter + raw MDX body (compiled at render time). */
export interface MdxDoc<TAcf = Record<string, unknown>> {
  slug: string;
  frontmatter: BaseFrontmatter<TAcf>;
  body: string;
}

/* ===================================================================================
 * A. HOMEPAGE  — front.php
 * =================================================================================== */
export interface ServiceCard {
  title: string;
  service_image?: string;
  description?: string;
  link?: string;                // CTA url (label paired below if present)
  link_label?: string;
}
export interface BrandLogo {
  image: string;
  url?: string;
}
export interface Testimonial {
  name: string;
  role?: string;
  avatar?: string;
  quote: string;
  rating?: number;
}
export interface FaqItem {
  question: string;
  answer: string;
}
export interface HomeAcf {
  banner_title?: string;
  banner_subtitle?: string;
  banner_button?: string;        // label
  banner_button_link?: string;   // url
  banner_button_one?: string;
  banner_button_one_link?: string;
  services?: ServiceCard[];      // repeater
  brands?: BrandLogo[];          // owl "brand_slide"
  testimonials?: Testimonial[];  // owl "testimonial_slide"
  faqs?: FaqItem[];              // footer accordion
  four_button?: string;
  four_button_link?: string;
  sectoin_6_button?: string;     // (sic) legacy typo preserved
}
export type HomePage = MdxDoc<HomeAcf>;

/* ===================================================================================
 * B. BUSINESS TOOL REVIEW — single-businesstool.php  (CPT: businesstool)
 * =================================================================================== */
export interface BusinessToolAcf {
  logo?: string;
  review_ster?: string | number;   // rating value, e.g. "5" / "4.5"  (sic: "ster")
  rating?: string | number;
  review_titie?: string;           // (sic) tagline, e.g. "Rated 4.5/5 on Trustpilot"
  // CTAs
  one_button?: string; one_button_link?: string;
  one_button_one?: string; one_button_one_link?: string;
  instant_sign_up?: string;
  // HTML content sections (rendered via <RichHtml/>, not MDX)
  overview_title?: string; overview_content?: string;
  features_content?: string; features_listing?: string;
  review_title?: string; review_content?: string; review_image?: string;
  services_section_title?: string; services_section_content?: string;
  videos_content?: string;
  alternatives_title?: string; alternatives_content?: string;
  faqs_title?: string; faqs_content?: string;
  // repeaters (overview_listing, review_area, faqs_section, services_section_list, …)
  // shapes vary per tool, so keep them loose:
  [key: string]: unknown;
}
export type BusinessToolReview = MdxDoc<BusinessToolAcf>;

/* ===================================================================================
 * C. CATEGORY ARCHIVE — taxonomy-bt_categories.php
 * =================================================================================== */
export interface CategoryAcf {
  intro?: string;
  hero_image?: string;
}
/** Lightweight tool card assembled at build time from the tool MDX in this category. */
export interface ToolCardRef {
  title: string;
  slug: string;
  route: string;
  logo?: string;
  rating?: number | string;
  excerpt?: string;
  affiliate_url?: string;
}
export interface ToolCategory {
  name: string;
  slug: string;
  route: string;                 // "/category/{slug}"
  description?: string;
  acf?: CategoryAcf;
  tools: ToolCardRef[];
}

/* ===================================================================================
 * URL PARITY — redirects/url-map.json
 * =================================================================================== */
export interface RedirectRule {
  source: string;        // legacy path, e.g. "/deel-review/"
  destination: string;   // new route, e.g. "/tools/deel"
  permanent: boolean;
  type?: PostType;
}
